import './globals.css'
import GlobalProvider from '@/providers/GlobalProvider';
import { Inter } from 'next/font/google'
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import Header from '@/components/Header';
import { CssBaseline } from '@mui/material';
import Theme from '@/providers/Theme';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CssBaseline />
        <Theme>
          <Header/>
          <GlobalProvider>
            {children}
          </GlobalProvider>
        </Theme>
      </body>
    </html>
  )
}
